---

interfaces:
        Loopback0:
                address: '192.168.100.1/32'
        Ethernet1:
                address: '10.10.10.1/31'
        Ethernet2:
                address: '10.10.10.9/31'
bgp:
        as_number: 64521
        router_id: '192.168.100.1'
        neighbors:
                10.10.10.0:
                        remote-as: 65500
                        ipv4: true
                        evpn: true
                        send-community: true
                        loopback: '192.168.101.1' 
                10.10.10.8:
                        remote-as: 65500
                        ipv4: true
                        evpn: true
                        send-community: true
                        loopback: '192.168.101.2'
vlans:
        100:
                vni: 10100
                name: 'VLAN100-VNI10100'
                interfaces:
                        - 'Ethernet3'
                rd: '192.168.100.1:1'
                export_rt: '100:100'
                import_rt: '100:100'
